### ISSUE TITLE
 I want to increase the screen sharing frame rate

### ISSUE THREAD

**Issue by wayhomeblue** [OpenVidu/openvidu-screen-sharing-chrome-extension#4]
I am Japanese. I can't speak English well, so please let me know if you don't understand the meaning.

I want to share the game screen, but the frame rate of the shared video is only about 10-20.

Is there any way to improve the frame rate?

Server: Ubuntu 16.04.5 LTS
Chrome: 78.0.3904.108

**Comment by micaelgallego** [comment]
Frame rate depends on browser you use. Google Chrome will choose it automatically based on your computer power. Firefox will use a fixed one.

**Comment by monavie1989** [comment]
How can I modify frameRate config of Screen Sharing extension

**Comment by micaelgallego** [comment]
Extension is no longer needed to share screen in Chrome with OpenVidu.
